export type LifecycleState = "submitted" | "accepted" | "rejected" | "working" | "input_required" | "completed" | "partial" | "failed" | "cancelled" | "budget_exhausted";
export type TerminalStatus = "completed" | "partial" | "failed" | "cancelled" | "budget_exhausted" | "rejected";
export type NetworkAuthority = { mode: "none" } | { mode: "bounded"; destinations: string[] } | { mode: "any" };
export interface CredentialGrant { handle: string; scopes?: string[] }
export interface Authority { capabilities: string[]; filesystem: { read: string[]; write: string[] }; network: NetworkAuthority; subprocess: { allowed: boolean; commands?: string[] }; credentials: CredentialGrant[]; sideEffects: string[]; approvals?: { action: string; required: boolean }[]; delegation: { allowed: boolean; maxDepth: number } }
export interface WorkspaceRef { id?: string; uri?: string; baseRevision?: string; mode: "shared" | "read_only" | "worktree" | "sandbox" | "remote"; allowedRoots?: { path: string; access: "read" | "write" | "read_write" }[] }
export interface AcceptanceCriterion { id: string; kind: "command" | "artifact" | "schema" | "assertion" | "external_evaluator" | "human_approval"; description: string; evaluator?: "worker" | "caller" | "external" | "human"; required?: boolean; [key: string]: unknown }
export interface Artifact { id: string; kind: string; mediaType: string; uri: string; digest: string; size: number; producerDelegationId: string; path?: string; metadata?: Record<string,string> }
export interface DelegationRequest { specVersion: "0.1"; id: string; parent?: { delegationId: string; workerId?: string; depth: number }; objective: { summary: string; details?: string }; context?: unknown[]; workspace?: WorkspaceRef; authority: Authority; constraints?: Record<string,unknown>; budget?: Record<string,number|string>; acceptanceCriteria?: AcceptanceCriterion[]; expectedArtifacts?: unknown[]; resultSchema?: unknown; scheduling?: unknown; metadata?: Record<string,string> }
export interface AcceptanceResult { criterionId: string; status: "passed" | "failed" | "not_run" | "needs_review"; evidenceArtifactIds?: string[]; message?: string; evaluator?: string }
export interface DelegationResult { specVersion: "0.1"; delegationId: string; status: TerminalStatus; summary?: string; output?: unknown; artifacts?: Artifact[]; acceptance?: AcceptanceResult[]; usage?: Record<string,number|string>; diagnostics?: { level: "info"|"warning"|"error"; code?: string; message: string }[]; metadata?: Record<string,string> }
export interface InputRequired { delegationId: string; requestId: string; reason: string; question: string; inputSchema?: unknown; deadline?: string; defaultBehavior?: string; partialArtifacts?: Artifact[]; remainingBudget?: Record<string,number>; resumeToken?: string }
export interface WorkerDescriptor { specVersion: "0.1"; id: string; name?: string; capabilities: string[]; authorityMax?: Authority; locality?: { kind: "local"|"remote"|"hybrid" }; supportedWorkspaceModes?: string[]; supportedFeatures?: Record<string,boolean>; metadata?: Record<string,string> }
